schema_version = "1.0.0"
id = "render_selected_strips"
version = "1.0.1"
name = "Render Selected Strips"
tagline = "Quickly render selected sequencer strips"
maintainer = "Tristan Weis"
type = "add-on"
website = "https://github.com/Plyrolith/render_selected_strips/"
tags = ["Sequencer"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]